# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user/profile.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user/profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user/profile.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb2\x02\n\x07Profile\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x18\n\x0bmiddle_name\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x17\n\navatar_url\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08timezone\x18\x06 \x01(\tH\x02\x88\x01\x01\x12\x13\n\x06locale\x18\x07 \x01(\tH\x03\x88\x01\x01\x12)\n\x08settings\x18\x08 \x01(\x0b\x32\x17.google.protobuf.Struct\x12.\n\nupdated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x0e\n\x0c_middle_nameB\r\n\x0b_avatar_urlB\x0b\n\t_timezoneB\t\n\x07_locale\"$\n\x11GetProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x98\x01\n\x14\x43reateProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x18\n\x0bmiddle_name\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06locale\x18\x05 \x01(\tH\x01\x88\x01\x01\x42\x0e\n\x0c_middle_nameB\t\n\x07_locale\"1\n\x0fProfileResponse\x12\x1e\n\x07profile\x18\x01 \x01(\x0b\x32\r.user.Profile2\x92\x01\n\x0eProfileService\x12<\n\nGetProfile\x12\x17.user.GetProfileRequest\x1a\x15.user.ProfileResponse\x12\x42\n\rCreateProfile\x12\x1a.user.CreateProfileRequest\x1a\x15.user.ProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROFILE']._serialized_start=92
  _globals['_PROFILE']._serialized_end=398
  _globals['_GETPROFILEREQUEST']._serialized_start=400
  _globals['_GETPROFILEREQUEST']._serialized_end=436
  _globals['_CREATEPROFILEREQUEST']._serialized_start=439
  _globals['_CREATEPROFILEREQUEST']._serialized_end=591
  _globals['_PROFILERESPONSE']._serialized_start=593
  _globals['_PROFILERESPONSE']._serialized_end=642
  _globals['_PROFILESERVICE']._serialized_start=645
  _globals['_PROFILESERVICE']._serialized_end=791
# @@protoc_insertion_point(module_scope)
