"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import typing
from . import profile_pb2

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ProfileServiceStub:
    """---------------------------------------------------------
    2. SERVICE DEFINITION (Python Side)
    ---------------------------------------------------------
    """

    @typing.overload
    def __new__(cls, channel: grpc.Channel) -> ProfileServiceStub: ...
    @typing.overload
    def __new__(cls, channel: grpc.aio.Channel) -> ProfileServiceAsyncStub: ...
    GetProfile: grpc.UnaryUnaryMultiCallable[profile_pb2.GetProfileRequest, profile_pb2.ProfileResponse]
    """Frontend calls this to get user details"""
    CreateProfile: grpc.UnaryUnaryMultiCallable[profile_pb2.CreateProfileRequest, profile_pb2.ProfileResponse]
    """Called internally or via Gateway to create the profile part"""

@typing.type_check_only
class ProfileServiceAsyncStub(ProfileServiceStub):
    """---------------------------------------------------------
    2. SERVICE DEFINITION (Python Side)
    ---------------------------------------------------------
    """

    def __init__(self, channel: grpc.aio.Channel) -> None: ...
    GetProfile: grpc.aio.UnaryUnaryMultiCallable[profile_pb2.GetProfileRequest, profile_pb2.ProfileResponse]  # type: ignore[assignment]
    """Frontend calls this to get user details"""
    CreateProfile: grpc.aio.UnaryUnaryMultiCallable[profile_pb2.CreateProfileRequest, profile_pb2.ProfileResponse]  # type: ignore[assignment]
    """Called internally or via Gateway to create the profile part"""

class ProfileServiceServicer(metaclass=abc.ABCMeta):
    """---------------------------------------------------------
    2. SERVICE DEFINITION (Python Side)
    ---------------------------------------------------------
    """

    @abc.abstractmethod
    def GetProfile(
        self,
        request: profile_pb2.GetProfileRequest,
        context: _ServicerContext,
    ) -> typing.Union[profile_pb2.ProfileResponse, collections.abc.Awaitable[profile_pb2.ProfileResponse]]:
        """Frontend calls this to get user details"""

    @abc.abstractmethod
    def CreateProfile(
        self,
        request: profile_pb2.CreateProfileRequest,
        context: _ServicerContext,
    ) -> typing.Union[profile_pb2.ProfileResponse, collections.abc.Awaitable[profile_pb2.ProfileResponse]]:
        """Called internally or via Gateway to create the profile part"""

def add_ProfileServiceServicer_to_server(servicer: ProfileServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
