"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.struct_pb2
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Profile(google.protobuf.message.Message):
    """---------------------------------------------------------
    1. DATA MODELS (Matches 'profiles' table)
    ---------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    FIRST_NAME_FIELD_NUMBER: builtins.int
    MIDDLE_NAME_FIELD_NUMBER: builtins.int
    LAST_NAME_FIELD_NUMBER: builtins.int
    AVATAR_URL_FIELD_NUMBER: builtins.int
    TIMEZONE_FIELD_NUMBER: builtins.int
    LOCALE_FIELD_NUMBER: builtins.int
    SETTINGS_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    """FK to Auth ID"""
    first_name: builtins.str
    middle_name: builtins.str
    last_name: builtins.str
    avatar_url: builtins.str
    timezone: builtins.str
    locale: builtins.str
    @property
    def settings(self) -> google.protobuf.struct_pb2.Struct:
        """JSONB"""

    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        first_name: builtins.str = ...,
        middle_name: builtins.str | None = ...,
        last_name: builtins.str = ...,
        avatar_url: builtins.str | None = ...,
        timezone: builtins.str | None = ...,
        locale: builtins.str | None = ...,
        settings: google.protobuf.struct_pb2.Struct | None = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["_avatar_url", b"_avatar_url", "_locale", b"_locale", "_middle_name", b"_middle_name", "_timezone", b"_timezone", "avatar_url", b"avatar_url", "locale", b"locale", "middle_name", b"middle_name", "settings", b"settings", "timezone", b"timezone", "updated_at", b"updated_at"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["_avatar_url", b"_avatar_url", "_locale", b"_locale", "_middle_name", b"_middle_name", "_timezone", b"_timezone", "avatar_url", b"avatar_url", "first_name", b"first_name", "last_name", b"last_name", "locale", b"locale", "middle_name", b"middle_name", "settings", b"settings", "timezone", b"timezone", "updated_at", b"updated_at", "user_id", b"user_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__avatar_url: typing_extensions.TypeAlias = typing.Literal["avatar_url"]
    _WhichOneofArgType__avatar_url: typing_extensions.TypeAlias = typing.Literal["_avatar_url", b"_avatar_url"]
    _WhichOneofReturnType__locale: typing_extensions.TypeAlias = typing.Literal["locale"]
    _WhichOneofArgType__locale: typing_extensions.TypeAlias = typing.Literal["_locale", b"_locale"]
    _WhichOneofReturnType__middle_name: typing_extensions.TypeAlias = typing.Literal["middle_name"]
    _WhichOneofArgType__middle_name: typing_extensions.TypeAlias = typing.Literal["_middle_name", b"_middle_name"]
    _WhichOneofReturnType__timezone: typing_extensions.TypeAlias = typing.Literal["timezone"]
    _WhichOneofArgType__timezone: typing_extensions.TypeAlias = typing.Literal["_timezone", b"_timezone"]
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__avatar_url) -> _WhichOneofReturnType__avatar_url | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__locale) -> _WhichOneofReturnType__locale | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__middle_name) -> _WhichOneofReturnType__middle_name | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__timezone) -> _WhichOneofReturnType__timezone | None: ...

Global___Profile: typing_extensions.TypeAlias = Profile

@typing.final
class GetProfileRequest(google.protobuf.message.Message):
    """---------------------------------------------------------
    3. DTOs
    ---------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["user_id", b"user_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetProfileRequest: typing_extensions.TypeAlias = GetProfileRequest

@typing.final
class CreateProfileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    FIRST_NAME_FIELD_NUMBER: builtins.int
    LAST_NAME_FIELD_NUMBER: builtins.int
    MIDDLE_NAME_FIELD_NUMBER: builtins.int
    LOCALE_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    """Passed from Auth Service result"""
    first_name: builtins.str
    last_name: builtins.str
    middle_name: builtins.str
    locale: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        first_name: builtins.str = ...,
        last_name: builtins.str = ...,
        middle_name: builtins.str | None = ...,
        locale: builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["_locale", b"_locale", "_middle_name", b"_middle_name", "locale", b"locale", "middle_name", b"middle_name"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["_locale", b"_locale", "_middle_name", b"_middle_name", "first_name", b"first_name", "last_name", b"last_name", "locale", b"locale", "middle_name", b"middle_name", "user_id", b"user_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__locale: typing_extensions.TypeAlias = typing.Literal["locale"]
    _WhichOneofArgType__locale: typing_extensions.TypeAlias = typing.Literal["_locale", b"_locale"]
    _WhichOneofReturnType__middle_name: typing_extensions.TypeAlias = typing.Literal["middle_name"]
    _WhichOneofArgType__middle_name: typing_extensions.TypeAlias = typing.Literal["_middle_name", b"_middle_name"]
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__locale) -> _WhichOneofReturnType__locale | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__middle_name) -> _WhichOneofReturnType__middle_name | None: ...

Global___CreateProfileRequest: typing_extensions.TypeAlias = CreateProfileRequest

@typing.final
class ProfileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROFILE_FIELD_NUMBER: builtins.int
    @property
    def profile(self) -> Global___Profile: ...
    def __init__(
        self,
        *,
        profile: Global___Profile | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["profile", b"profile"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["profile", b"profile"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ProfileResponse: typing_extensions.TypeAlias = ProfileResponse
