"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _UserStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _UserStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UserStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STATUS_UNSPECIFIED: _UserStatus.ValueType  # 0
    ACTIVE: _UserStatus.ValueType  # 1
    INACTIVE: _UserStatus.ValueType  # 2
    SUSPENDED: _UserStatus.ValueType  # 3
    DELETED: _UserStatus.ValueType  # 4

class UserStatus(_UserStatus, metaclass=_UserStatusEnumTypeWrapper):
    """2. ENUMS"""

STATUS_UNSPECIFIED: UserStatus.ValueType  # 0
ACTIVE: UserStatus.ValueType  # 1
INACTIVE: UserStatus.ValueType  # 2
SUSPENDED: UserStatus.ValueType  # 3
DELETED: UserStatus.ValueType  # 4
Global___UserStatus: typing_extensions.TypeAlias = UserStatus

class _AuthProvider:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AuthProviderEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AuthProvider.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LOCAL: _AuthProvider.ValueType  # 0
    GOOGLE: _AuthProvider.ValueType  # 1
    MICROSOFT: _AuthProvider.ValueType  # 2
    APPLE: _AuthProvider.ValueType  # 3

class AuthProvider(_AuthProvider, metaclass=_AuthProviderEnumTypeWrapper): ...

LOCAL: AuthProvider.ValueType  # 0
GOOGLE: AuthProvider.ValueType  # 1
MICROSOFT: AuthProvider.ValueType  # 2
APPLE: AuthProvider.ValueType  # 3
Global___AuthProvider: typing_extensions.TypeAlias = AuthProvider

@typing.final
class User(google.protobuf.message.Message):
    """1. THE ENTITY (Mirrors the database table)"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    FIRST_NAME_FIELD_NUMBER: builtins.int
    MIDDLE_NAME_FIELD_NUMBER: builtins.int
    LAST_NAME_FIELD_NUMBER: builtins.int
    PASSWORD_HASH_FIELD_NUMBER: builtins.int
    AUTH_PROVIDER_FIELD_NUMBER: builtins.int
    AUTH_SUBJECT_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    MFA_ENABLED_FIELD_NUMBER: builtins.int
    TIMEZONE_FIELD_NUMBER: builtins.int
    LOCALE_FIELD_NUMBER: builtins.int
    AVATAR_URL_FIELD_NUMBER: builtins.int
    SETTINGS_JSON_FIELD_NUMBER: builtins.int
    EMAIL_VERIFIED_AT_FIELD_NUMBER: builtins.int
    LAST_LOGIN_AT_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    DELETED_AT_FIELD_NUMBER: builtins.int
    id: builtins.str
    email: builtins.str
    first_name: builtins.str
    """Name fields"""
    middle_name: builtins.str
    last_name: builtins.str
    password_hash: builtins.str
    """Security fields"""
    auth_provider: Global___AuthProvider.ValueType
    auth_subject: builtins.str
    status: Global___UserStatus.ValueType
    """State fields"""
    mfa_enabled: builtins.bool
    timezone: builtins.str
    """Preference fields"""
    locale: builtins.str
    avatar_url: builtins.str
    settings_json: builtins.str
    """Default is "" -> SQL default is {}"""
    @property
    def email_verified_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamps"""

    @property
    def last_login_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def deleted_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        email: builtins.str = ...,
        first_name: builtins.str = ...,
        middle_name: builtins.str | None = ...,
        last_name: builtins.str = ...,
        password_hash: builtins.str = ...,
        auth_provider: Global___AuthProvider.ValueType = ...,
        auth_subject: builtins.str | None = ...,
        status: Global___UserStatus.ValueType = ...,
        mfa_enabled: builtins.bool = ...,
        timezone: builtins.str | None = ...,
        locale: builtins.str | None = ...,
        avatar_url: builtins.str | None = ...,
        settings_json: builtins.str = ...,
        email_verified_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        last_login_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        deleted_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["_auth_subject", b"_auth_subject", "_avatar_url", b"_avatar_url", "_deleted_at", b"_deleted_at", "_email_verified_at", b"_email_verified_at", "_last_login_at", b"_last_login_at", "_locale", b"_locale", "_middle_name", b"_middle_name", "_timezone", b"_timezone", "auth_subject", b"auth_subject", "avatar_url", b"avatar_url", "created_at", b"created_at", "deleted_at", b"deleted_at", "email_verified_at", b"email_verified_at", "last_login_at", b"last_login_at", "locale", b"locale", "middle_name", b"middle_name", "timezone", b"timezone", "updated_at", b"updated_at"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["_auth_subject", b"_auth_subject", "_avatar_url", b"_avatar_url", "_deleted_at", b"_deleted_at", "_email_verified_at", b"_email_verified_at", "_last_login_at", b"_last_login_at", "_locale", b"_locale", "_middle_name", b"_middle_name", "_timezone", b"_timezone", "auth_provider", b"auth_provider", "auth_subject", b"auth_subject", "avatar_url", b"avatar_url", "created_at", b"created_at", "deleted_at", b"deleted_at", "email", b"email", "email_verified_at", b"email_verified_at", "first_name", b"first_name", "id", b"id", "last_login_at", b"last_login_at", "last_name", b"last_name", "locale", b"locale", "mfa_enabled", b"mfa_enabled", "middle_name", b"middle_name", "password_hash", b"password_hash", "settings_json", b"settings_json", "status", b"status", "timezone", b"timezone", "updated_at", b"updated_at"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__auth_subject: typing_extensions.TypeAlias = typing.Literal["auth_subject"]
    _WhichOneofArgType__auth_subject: typing_extensions.TypeAlias = typing.Literal["_auth_subject", b"_auth_subject"]
    _WhichOneofReturnType__avatar_url: typing_extensions.TypeAlias = typing.Literal["avatar_url"]
    _WhichOneofArgType__avatar_url: typing_extensions.TypeAlias = typing.Literal["_avatar_url", b"_avatar_url"]
    _WhichOneofReturnType__deleted_at: typing_extensions.TypeAlias = typing.Literal["deleted_at"]
    _WhichOneofArgType__deleted_at: typing_extensions.TypeAlias = typing.Literal["_deleted_at", b"_deleted_at"]
    _WhichOneofReturnType__email_verified_at: typing_extensions.TypeAlias = typing.Literal["email_verified_at"]
    _WhichOneofArgType__email_verified_at: typing_extensions.TypeAlias = typing.Literal["_email_verified_at", b"_email_verified_at"]
    _WhichOneofReturnType__last_login_at: typing_extensions.TypeAlias = typing.Literal["last_login_at"]
    _WhichOneofArgType__last_login_at: typing_extensions.TypeAlias = typing.Literal["_last_login_at", b"_last_login_at"]
    _WhichOneofReturnType__locale: typing_extensions.TypeAlias = typing.Literal["locale"]
    _WhichOneofArgType__locale: typing_extensions.TypeAlias = typing.Literal["_locale", b"_locale"]
    _WhichOneofReturnType__middle_name: typing_extensions.TypeAlias = typing.Literal["middle_name"]
    _WhichOneofArgType__middle_name: typing_extensions.TypeAlias = typing.Literal["_middle_name", b"_middle_name"]
    _WhichOneofReturnType__timezone: typing_extensions.TypeAlias = typing.Literal["timezone"]
    _WhichOneofArgType__timezone: typing_extensions.TypeAlias = typing.Literal["_timezone", b"_timezone"]
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__auth_subject) -> _WhichOneofReturnType__auth_subject | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__avatar_url) -> _WhichOneofReturnType__avatar_url | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__deleted_at) -> _WhichOneofReturnType__deleted_at | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__email_verified_at) -> _WhichOneofReturnType__email_verified_at | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__last_login_at) -> _WhichOneofReturnType__last_login_at | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__locale) -> _WhichOneofReturnType__locale | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__middle_name) -> _WhichOneofReturnType__middle_name | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__timezone) -> _WhichOneofReturnType__timezone | None: ...

Global___User: typing_extensions.TypeAlias = User

@typing.final
class GetUserByIdRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["id", b"id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetUserByIdRequest: typing_extensions.TypeAlias = GetUserByIdRequest

@typing.final
class GetUserByEmailRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    email: builtins.str
    def __init__(
        self,
        *,
        email: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["email", b"email"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetUserByEmailRequest: typing_extensions.TypeAlias = GetUserByEmailRequest

@typing.final
class UserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_FIELD_NUMBER: builtins.int
    @property
    def user(self) -> Global___User: ...
    def __init__(
        self,
        *,
        user: Global___User | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["user", b"user"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["user", b"user"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UserResponse: typing_extensions.TypeAlias = UserResponse

@typing.final
class CreateUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    FIRST_NAME_FIELD_NUMBER: builtins.int
    MIDDLE_NAME_FIELD_NUMBER: builtins.int
    LAST_NAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    AUTH_PROVIDER_FIELD_NUMBER: builtins.int
    AUTH_SUBJECT_FIELD_NUMBER: builtins.int
    TIMEZONE_FIELD_NUMBER: builtins.int
    LOCALE_FIELD_NUMBER: builtins.int
    AVATAR_URL_FIELD_NUMBER: builtins.int
    email: builtins.str
    first_name: builtins.str
    middle_name: builtins.str
    last_name: builtins.str
    password: builtins.str
    auth_provider: Global___AuthProvider.ValueType
    auth_subject: builtins.str
    timezone: builtins.str
    locale: builtins.str
    avatar_url: builtins.str
    def __init__(
        self,
        *,
        email: builtins.str = ...,
        first_name: builtins.str = ...,
        middle_name: builtins.str | None = ...,
        last_name: builtins.str = ...,
        password: builtins.str = ...,
        auth_provider: Global___AuthProvider.ValueType = ...,
        auth_subject: builtins.str | None = ...,
        timezone: builtins.str | None = ...,
        locale: builtins.str | None = ...,
        avatar_url: builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["_auth_subject", b"_auth_subject", "_avatar_url", b"_avatar_url", "_locale", b"_locale", "_middle_name", b"_middle_name", "_timezone", b"_timezone", "auth_subject", b"auth_subject", "avatar_url", b"avatar_url", "locale", b"locale", "middle_name", b"middle_name", "timezone", b"timezone"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["_auth_subject", b"_auth_subject", "_avatar_url", b"_avatar_url", "_locale", b"_locale", "_middle_name", b"_middle_name", "_timezone", b"_timezone", "auth_provider", b"auth_provider", "auth_subject", b"auth_subject", "avatar_url", b"avatar_url", "email", b"email", "first_name", b"first_name", "last_name", b"last_name", "locale", b"locale", "middle_name", b"middle_name", "password", b"password", "timezone", b"timezone"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__auth_subject: typing_extensions.TypeAlias = typing.Literal["auth_subject"]
    _WhichOneofArgType__auth_subject: typing_extensions.TypeAlias = typing.Literal["_auth_subject", b"_auth_subject"]
    _WhichOneofReturnType__avatar_url: typing_extensions.TypeAlias = typing.Literal["avatar_url"]
    _WhichOneofArgType__avatar_url: typing_extensions.TypeAlias = typing.Literal["_avatar_url", b"_avatar_url"]
    _WhichOneofReturnType__locale: typing_extensions.TypeAlias = typing.Literal["locale"]
    _WhichOneofArgType__locale: typing_extensions.TypeAlias = typing.Literal["_locale", b"_locale"]
    _WhichOneofReturnType__middle_name: typing_extensions.TypeAlias = typing.Literal["middle_name"]
    _WhichOneofArgType__middle_name: typing_extensions.TypeAlias = typing.Literal["_middle_name", b"_middle_name"]
    _WhichOneofReturnType__timezone: typing_extensions.TypeAlias = typing.Literal["timezone"]
    _WhichOneofArgType__timezone: typing_extensions.TypeAlias = typing.Literal["_timezone", b"_timezone"]
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__auth_subject) -> _WhichOneofReturnType__auth_subject | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__avatar_url) -> _WhichOneofReturnType__avatar_url | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__locale) -> _WhichOneofReturnType__locale | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__middle_name) -> _WhichOneofReturnType__middle_name | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__timezone) -> _WhichOneofReturnType__timezone | None: ...

Global___CreateUserRequest: typing_extensions.TypeAlias = CreateUserRequest
