"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _AuthProvider:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AuthProviderEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AuthProvider.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LOCAL: _AuthProvider.ValueType  # 0
    GOOGLE: _AuthProvider.ValueType  # 1
    MICROSOFT: _AuthProvider.ValueType  # 2
    APPLE: _AuthProvider.ValueType  # 3

class AuthProvider(_AuthProvider, metaclass=_AuthProviderEnumTypeWrapper):
    """---------------------------------------------------------
    1. DATA MODELS
    ---------------------------------------------------------
    """

LOCAL: AuthProvider.ValueType  # 0
GOOGLE: AuthProvider.ValueType  # 1
MICROSOFT: AuthProvider.ValueType  # 2
APPLE: AuthProvider.ValueType  # 3
Global___AuthProvider: typing_extensions.TypeAlias = AuthProvider

@typing.final
class CreateCredentialRequest(google.protobuf.message.Message):
    """---------------------------------------------------------
    3. DTOs
    ---------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    PROVIDER_FIELD_NUMBER: builtins.int
    AUTH_SUBJECT_FIELD_NUMBER: builtins.int
    email: builtins.str
    password: builtins.str
    """Raw password (sent over mTLS)"""
    provider: Global___AuthProvider.ValueType
    auth_subject: builtins.str
    """For 3rd party providers"""
    def __init__(
        self,
        *,
        email: builtins.str = ...,
        password: builtins.str = ...,
        provider: Global___AuthProvider.ValueType = ...,
        auth_subject: builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["_auth_subject", b"_auth_subject", "auth_subject", b"auth_subject"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["_auth_subject", b"_auth_subject", "auth_subject", b"auth_subject", "email", b"email", "password", b"password", "provider", b"provider"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__auth_subject: typing_extensions.TypeAlias = typing.Literal["auth_subject"]
    _WhichOneofArgType__auth_subject: typing_extensions.TypeAlias = typing.Literal["_auth_subject", b"_auth_subject"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType__auth_subject) -> _WhichOneofReturnType__auth_subject | None: ...

Global___CreateCredentialRequest: typing_extensions.TypeAlias = CreateCredentialRequest

@typing.final
class CreateCredentialResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    """The UUIDv7 generated by Java"""
    email: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        email: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["email", b"email", "user_id", b"user_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateCredentialResponse: typing_extensions.TypeAlias = CreateCredentialResponse

@typing.final
class ValidateCredentialRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    email: builtins.str
    password: builtins.str
    def __init__(
        self,
        *,
        email: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["email", b"email", "password", b"password"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ValidateCredentialRequest: typing_extensions.TypeAlias = ValidateCredentialRequest

@typing.final
class ValidateCredentialResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    token: builtins.str
    """JWT"""
    user_id: builtins.str
    def __init__(
        self,
        *,
        token: builtins.str = ...,
        user_id: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["token", b"token", "user_id", b"user_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ValidateCredentialResponse: typing_extensions.TypeAlias = ValidateCredentialResponse

@typing.final
class DeleteCredentialRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["user_id", b"user_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteCredentialRequest: typing_extensions.TypeAlias = DeleteCredentialRequest

@typing.final
class DeleteCredentialResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["success", b"success"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteCredentialResponse: typing_extensions.TypeAlias = DeleteCredentialResponse
