"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
from . import auth_pb2
import collections.abc
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class AuthServiceStub:
    """---------------------------------------------------------
    2. SERVICE DEFINITION (Java Side)
    ---------------------------------------------------------

    Python user service calls this during registration
    """

    @typing.overload
    def __new__(cls, channel: grpc.Channel) -> AuthServiceStub: ...
    @typing.overload
    def __new__(cls, channel: grpc.aio.Channel) -> AuthServiceAsyncStub: ...
    CreateCredential: grpc.UnaryUnaryMultiCallable[auth_pb2.CreateCredentialRequest, auth_pb2.CreateCredentialResponse]
    ValidateCredential: grpc.UnaryUnaryMultiCallable[auth_pb2.ValidateCredentialRequest, auth_pb2.ValidateCredentialResponse]
    """Frontend/Gateway calls this for login"""
    DeleteCredential: grpc.UnaryUnaryMultiCallable[auth_pb2.DeleteCredentialRequest, auth_pb2.DeleteCredentialResponse]
    """Python user service calls this to cleanup if profile creation fails (saga compensation)"""

@typing.type_check_only
class AuthServiceAsyncStub(AuthServiceStub):
    """---------------------------------------------------------
    2. SERVICE DEFINITION (Java Side)
    ---------------------------------------------------------

    Python user service calls this during registration
    """

    def __init__(self, channel: grpc.aio.Channel) -> None: ...
    CreateCredential: grpc.aio.UnaryUnaryMultiCallable[auth_pb2.CreateCredentialRequest, auth_pb2.CreateCredentialResponse]  # type: ignore[assignment]
    ValidateCredential: grpc.aio.UnaryUnaryMultiCallable[auth_pb2.ValidateCredentialRequest, auth_pb2.ValidateCredentialResponse]  # type: ignore[assignment]
    """Frontend/Gateway calls this for login"""
    DeleteCredential: grpc.aio.UnaryUnaryMultiCallable[auth_pb2.DeleteCredentialRequest, auth_pb2.DeleteCredentialResponse]  # type: ignore[assignment]
    """Python user service calls this to cleanup if profile creation fails (saga compensation)"""

class AuthServiceServicer(metaclass=abc.ABCMeta):
    """---------------------------------------------------------
    2. SERVICE DEFINITION (Java Side)
    ---------------------------------------------------------

    Python user service calls this during registration
    """

    @abc.abstractmethod
    def CreateCredential(
        self,
        request: auth_pb2.CreateCredentialRequest,
        context: _ServicerContext,
    ) -> typing.Union[auth_pb2.CreateCredentialResponse, collections.abc.Awaitable[auth_pb2.CreateCredentialResponse]]: ...

    @abc.abstractmethod
    def ValidateCredential(
        self,
        request: auth_pb2.ValidateCredentialRequest,
        context: _ServicerContext,
    ) -> typing.Union[auth_pb2.ValidateCredentialResponse, collections.abc.Awaitable[auth_pb2.ValidateCredentialResponse]]:
        """Frontend/Gateway calls this for login"""

    @abc.abstractmethod
    def DeleteCredential(
        self,
        request: auth_pb2.DeleteCredentialRequest,
        context: _ServicerContext,
    ) -> typing.Union[auth_pb2.DeleteCredentialResponse, collections.abc.Awaitable[auth_pb2.DeleteCredentialResponse]]:
        """Python user service calls this to cleanup if profile creation fails (saga compensation)"""

def add_AuthServiceServicer_to_server(servicer: AuthServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
