# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61uth/auth.proto\x12\x04\x61uth\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x01\n\x17\x43reateCredentialRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12$\n\x08provider\x18\x03 \x01(\x0e\x32\x12.auth.AuthProvider\x12\x19\n\x0c\x61uth_subject\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_auth_subject\":\n\x18\x43reateCredentialResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"<\n\x19ValidateCredentialRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"<\n\x1aValidateCredentialResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"*\n\x17\x44\x65leteCredentialRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"+\n\x18\x44\x65leteCredentialResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08*?\n\x0c\x41uthProvider\x12\t\n\x05LOCAL\x10\x00\x12\n\n\x06GOOGLE\x10\x01\x12\r\n\tMICROSOFT\x10\x02\x12\t\n\x05\x41PPLE\x10\x03\x32\x8c\x02\n\x0b\x41uthService\x12Q\n\x10\x43reateCredential\x12\x1d.auth.CreateCredentialRequest\x1a\x1e.auth.CreateCredentialResponse\x12W\n\x12ValidateCredential\x12\x1f.auth.ValidateCredentialRequest\x1a .auth.ValidateCredentialResponse\x12Q\n\x10\x44\x65leteCredential\x12\x1d.auth.DeleteCredentialRequest\x1a\x1e.auth.DeleteCredentialResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHPROVIDER']._serialized_start=474
  _globals['_AUTHPROVIDER']._serialized_end=537
  _globals['_CREATECREDENTIALREQUEST']._serialized_start=59
  _globals['_CREATECREDENTIALREQUEST']._serialized_end=199
  _globals['_CREATECREDENTIALRESPONSE']._serialized_start=201
  _globals['_CREATECREDENTIALRESPONSE']._serialized_end=259
  _globals['_VALIDATECREDENTIALREQUEST']._serialized_start=261
  _globals['_VALIDATECREDENTIALREQUEST']._serialized_end=321
  _globals['_VALIDATECREDENTIALRESPONSE']._serialized_start=323
  _globals['_VALIDATECREDENTIALRESPONSE']._serialized_end=383
  _globals['_DELETECREDENTIALREQUEST']._serialized_start=385
  _globals['_DELETECREDENTIALREQUEST']._serialized_end=427
  _globals['_DELETECREDENTIALRESPONSE']._serialized_start=429
  _globals['_DELETECREDENTIALRESPONSE']._serialized_end=472
  _globals['_AUTHSERVICE']._serialized_start=540
  _globals['_AUTHSERVICE']._serialized_end=808
# @@protoc_insertion_point(module_scope)
