# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import auth_pb2 as auth_dot_auth__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auth/auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """---------------------------------------------------------
    2. SERVICE DEFINITION (Java Side)
    ---------------------------------------------------------

    Python user service calls this during registration
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCredential = channel.unary_unary(
                '/auth.AuthService/CreateCredential',
                request_serializer=auth_dot_auth__pb2.CreateCredentialRequest.SerializeToString,
                response_deserializer=auth_dot_auth__pb2.CreateCredentialResponse.FromString,
                _registered_method=True)
        self.ValidateCredential = channel.unary_unary(
                '/auth.AuthService/ValidateCredential',
                request_serializer=auth_dot_auth__pb2.ValidateCredentialRequest.SerializeToString,
                response_deserializer=auth_dot_auth__pb2.ValidateCredentialResponse.FromString,
                _registered_method=True)
        self.DeleteCredential = channel.unary_unary(
                '/auth.AuthService/DeleteCredential',
                request_serializer=auth_dot_auth__pb2.DeleteCredentialRequest.SerializeToString,
                response_deserializer=auth_dot_auth__pb2.DeleteCredentialResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """---------------------------------------------------------
    2. SERVICE DEFINITION (Java Side)
    ---------------------------------------------------------

    Python user service calls this during registration
    """

    def CreateCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateCredential(self, request, context):
        """Frontend/Gateway calls this for login
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCredential(self, request, context):
        """Python user service calls this to cleanup if profile creation fails (saga compensation)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCredential,
                    request_deserializer=auth_dot_auth__pb2.CreateCredentialRequest.FromString,
                    response_serializer=auth_dot_auth__pb2.CreateCredentialResponse.SerializeToString,
            ),
            'ValidateCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateCredential,
                    request_deserializer=auth_dot_auth__pb2.ValidateCredentialRequest.FromString,
                    response_serializer=auth_dot_auth__pb2.ValidateCredentialResponse.SerializeToString,
            ),
            'DeleteCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCredential,
                    request_deserializer=auth_dot_auth__pb2.DeleteCredentialRequest.FromString,
                    response_serializer=auth_dot_auth__pb2.DeleteCredentialResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """---------------------------------------------------------
    2. SERVICE DEFINITION (Java Side)
    ---------------------------------------------------------

    Python user service calls this during registration
    """

    @staticmethod
    def CreateCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CreateCredential',
            auth_dot_auth__pb2.CreateCredentialRequest.SerializeToString,
            auth_dot_auth__pb2.CreateCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ValidateCredential',
            auth_dot_auth__pb2.ValidateCredentialRequest.SerializeToString,
            auth_dot_auth__pb2.ValidateCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/DeleteCredential',
            auth_dot_auth__pb2.DeleteCredentialRequest.SerializeToString,
            auth_dot_auth__pb2.DeleteCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
